AWSTemplateFormatVersion: 2010-09-09

Description: >
  This is the main indie.ninja stack template which all others will be included.
  This stack will create the ECS cluster, Service, Loadbalancer and lambda functions
  needed.


Parameters:
  LaunchType:
    Type: String
    Default: EC2
    AllowedValues:
      - Fargate
      - EC2
    Description: >
      The launch type for your service. Selecting EC2 will create an Auto
      Scaling group of t2.micro instances for your cluster. See
      https://docs.aws.amazon.com/AmazonECS/latest/developerguide/launch_types.html
      to learn more about launch types.

  GitHubUser:
    Type: String
    Description: Your username on GitHub.

  GitHubRepo:
    Type: String
    Description: The repo name of the application.

  GitHubAwsRepo:
    Type: String
    Description: The repo name of the repository containing the cloudformation stack

  GitHubBranch:
    Type: String
    Default: master
    Description: The branch of the repo to continuously deploy.

  TemplateBucket:
    Type: String
    Default: indie-ninja-cloudformation-templates
    Description: >
      The S3 bucket from which to fetch the templates used by this stack.

  ApplicationImageTag:
    Type: String
    Description: The commit hash of the Ecr image or latest for the latest
    Default: latest

  ApplicationEnv:
    Type: String
    Description: The environment to start the Application in
    Default: production

  ServiceName:
    Type: String
    Default: indie-ninja-api-service

  ApplicationImageId:
    Type: String
    Description: ECS Amazon Machine Image (AMI) ID

  EcrRepositoryNamespace:
    Type: String
    Description: The namespace of the Elastic Container Repo

  EcrRepositoryArn:
    Type: String
    Description: The Arn of the Elastic Container Repo

Metadata:
  AWS::CloudFormation::Interface:
    ParameterLabels:
      GitHubUser:
        default: "User"
      GitHubRepo:
        default: "Repo"
      GitHubBranch:
        default: "Branch"
      LaunchType:
        default: "Launch Type"
    ParameterGroups:
      - Label:
          default: Cluster Configuration
        Parameters:
          - LaunchType
      - Label:
          default: GitHub Configuration
        Parameters:
          - GitHubRepo
          - GitHubBranch
          - GitHubUser
      - Label:
          default: Stack Configuration
        Parameters:
          - TemplateBucket

Resources:
  Secrets:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${TemplateBucket}/secrets.yaml"
      Parameters:
        StackName: !Ref AWS::StackName

  Cluster:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${TemplateBucket}/cluster.yaml"
      Parameters:
        StackName: !Ref AWS::StackName
        Subnets: !GetAtt VPC.Outputs.Subnets
        VpcId: !GetAtt VPC.Outputs.VpcId
        ApplicationImageId: !Ref ApplicationImageId


  LoadBalancer:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${TemplateBucket}/load-balancer.yaml"
      Parameters:
        Subnets: !GetAtt VPC.Outputs.Subnets
        VpcId: !GetAtt VPC.Outputs.VpcId
        AutoScalingSecurityGroup: !GetAtt Cluster.Outputs.AutoScalingSecurityGroup
        StackName: !Ref AWS::StackName

  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${TemplateBucket}/vpc.yaml"
      Parameters:
        Name: !Ref AWS::StackName
        VpcCIDR: 10.215.0.0/16
        Subnet1CIDR: 10.215.10.0/24
        Subnet2CIDR: 10.215.20.0/24

  Database:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${TemplateBucket}/datatbase.yaml"
      Parameters:
        DatabasePassword: !GetAtt Secrets.Outputs.DatabasePassword
        Subnets: !GetAtt VPC.Outputs.Subnets
        VpcId: !GetAtt VPC.Outputs.VpcId
        AutoScalingSecurityGroup: !GetAtt Cluster.Outputs.AutoScalingSecurityGroup
        StackName: !Ref AWS::StackName

  TaskDefinitions:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${TemplateBucket}/task-definitions.yaml"
      Parameters:
        ApplicationEnv: !Ref ApplicationEnv
        ApplicationImageTag: !Ref ApplicationImageTag
        ClusterName: !GetAtt Cluster.Outputs.ClusterName
        ClusterArn: !GetAtt Cluster.Outputs.ClusterArn
        DatabaseAddress: !GetAtt Database.Outputs.DatabaseAddress
        AutoScalingGroupName: !GetAtt Cluster.Outputs.AutoScalingGroupName
        EcrRepositoryNamespace: !Ref EcrRepositoryNamespace
        StackName: !Ref AWS::StackName

  Service:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${TemplateBucket}/service.yaml"
      Parameters:
        StackName: !Ref AWS::StackName
        ServiceName: !Ref ServiceName
        ClusterName: !GetAtt Cluster.Outputs.ClusterName
        ClusterArn: !GetAtt Cluster.Outputs.ClusterArn
        MigrateTaskArn: !GetAtt TaskDefinitions.Outputs.MigrateTaskArn
        AutoScalingGroupName: !GetAtt Cluster.Outputs.AutoScalingGroupName
        ApplicationLogGroupName: !GetAtt Cluster.Outputs.ApplicationLogGroupName
        LoadBalancerHttpListener: !GetAtt LoadBalancer.Outputs.LoadBalancerHttpListenerArn
        ApplicationTaskDefinitionArn: !GetAtt TaskDefinitions.Outputs.ApplicationTaskDefinitionArn
        TargetGroupArn: !GetAtt LoadBalancer.Outputs.TargetGroupArn

  CodePipeline:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${TemplateBucket}/codepipeline.yaml"
      Parameters:
        StackName: !Ref AWS::StackName
        ClusterName: !GetAtt Cluster.Outputs.ClusterName
        ServiceArn: !GetAtt Service.Outputs.Service
        EcrRepositoryNamespace: !Ref EcrRepositoryNamespace
        GitHubUser: !Ref GitHubUser
        GitHubToken: !GetAtt Secrets.Outputs.GitHubToken
        GitHubRepo: !Ref GitHubRepo
        GitHubBranch: !Ref GitHubBranch
        EcrRepositoryArn: !Ref EcrRepositoryArn
        EcrRepositoryNamespace: !Ref EcrRepositoryNamespace
        GitHubAwsRepo: !Ref GitHubAwsRepo

Outputs:
  PipelineUrl:
    Description: The continuous deployment pipeline in the AWS Management Console.
    Value: !GetAtt CodePipeline.Outputs.PipelineUrl

  ServiceUrl:
    Description: The sample service that is being continuously deployed.
    Value: !GetAtt LoadBalancer.Outputs.ServiceUrl

